# Generated by Django 6.0.4 on 2026-05-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва фільму')),
                ('description', models.TextField(verbose_name='Опис фільму')),
                ('release_date', models.DateField(verbose_name='Дата виходу')),
                ('country', models.CharField(max_length=100, verbose_name='Країна')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-release_date', '-id'],
            },
        ),
    ]
