# Generated by Django 6.0.4 on 2026-05-25 16:04

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('created_at', models.DateField(default=datetime.datetime.now, verbose_name='Дата створення')),
                ('deleted_at', models.DateField(null=True, verbose_name='Дата видалення')),
            ],
            options={
                'db_table': 'dj_categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Назва товару')),
                ('price', models.FloatField(verbose_name='Ціна')),
                ('description', models.TextField(null=True, verbose_name='Опис товару')),
                ('image_path', models.URLField(blank=True, max_length=255, null=True, verbose_name='Картинка')),
                ('created_at', models.DateField(default=datetime.datetime.now, verbose_name='Дата створення')),
                ('deleted_at', models.DateField(null=True, verbose_name='Дата видалення')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='core.tag')),
            ],
            options={
                'verbose_name': 'Товар',
                'db_table': 'dj_products',
                'permissions': [('my_permission', 'Can do something')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='price_gt_zero')],
            },
        ),
    ]
