# Generated by Django 6.0.4 on 2026-05-22 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag_product_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('my_permission', 'Can do something')], 'verbose_name': 'Товар'},
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='category',
            name='deleted_at',
            field=models.DateField(null=True, verbose_name='Дата видалення'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateField(null=True, verbose_name='Дата видалення'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='Опис товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Тег'),
        ),
    ]
