# Generated by Django 6.0.4 on 2026-05-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_images_newspaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(default='assets/news/ill-01.svg', max_length=300, verbose_name='Зображення (шлях у static)'),
        ),
    ]
