# Generated by Django 6.0.4 on 2026-05-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_article_images_jpg_themed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(default='assets/news/politika-biudzhet.jpg', max_length=300, verbose_name='Зображення (шлях у static)'),
        ),
    ]
